tasks:
  - init: |
      docker-compose up
ports:
  - port: 3000
    onOpen: open-browser
  - port: 7474
    onOpen: ignore
  - port: 7687
    onOpen: ignore
  - port: 7473
    onOpen: ignore
  - port: 27017
    onOpen: ignore
  - port: 4000
    onOpen: ignore

vscode:
  extensions:
    - ms-azuretools.vscode-docker