version: "3"
services:
  decision-support-server:
    build: ./backend
    ports:
      - 80:80
    volumes:
      - ./backend/app:/code/app

    depends_on:
      - "mongodb"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
    volumes:
      - ./data/:/data/db
    ports:
        - "27017:27017"
  neo4j:
    image: neo4j:5.3.0
    container_name: neo4j    
    environment:
      - NEO4J_PLUGINS=["graph-data-science"]
      - NEO4J_dbms_security_procedures_allowlist=gds.*
      - NEO4J_dbms_security_auth__minimum__password__length=3
      - NEO4J_AUTH=neo4j/123
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/import:/var/lib/neo4j/import
      - ./neo4j/plugins:/plugins
    ports:
        - "7474:7474"
        - "7687:7687"
        - "7473:7473"
  decision-support-client:
    build: ./frontend
    container_name: decision-support-client    
    environment:
    # expecting to be in the TUM VPN
      - BACKEND_URL=0.0.0.0
      - VARIANT_NEO4J_URL=0.0.0.0
      - DE_NEO4J_URL=10.195.6.112
    volumes:
      - ./frontend/src:/app/src
    ports:
        - "3000:3000"
    depends_on:
      - "decision-support-server"
      - "mongodb"
      - "neo4j"
    command: npm start




