version: "3"
services:
  decision-support-server:
    build: ./backend
    ports:
      - 80:80
    volumes:
      - ./backend/app:/code/app
    depends_on:
      - "mongodb"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
    volumes:
      - ./data/:/data/db
    ports:
        - "27017:27017"
  neo4j:
    image: neo4j:latest
    container_name: neo4j    
    environment:
      - NEO4J_AUTH=neo4j/123
      - NEO4JLABS_PLUGINS=[\"apoc\"\]
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_export_file_enabled=true
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/import:/var/lib/neo4j/import
      - ./neo4j/plugins:/plugins
    ports:
        - "7474:7474"
        - "7687:7687"
        - "7473:7473"



